<a href="https://colab.research.google.com/github/mariawandhare/data_science_66/blob/main/Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Input size of square matrix
n = int(input("Enter size of square matrix: "))

# Input matrix elements
matrix = []
print("Enter matrix elements row by row:")
for i in range(n):
    row = []
    for j in range(n):
        row.append(float(input()))
    matrix.append(row)

# Convert list to NumPy array
matrix = np.array(matrix)

# Display matrix
print("Matrix is:")
print(matrix)

# Calculate determinant
determinant = np.linalg.det(matrix)

# Display determinant
print("Determinant of the matrix is:", determinant)


Enter size of square matrix: 2
Enter matrix elements row by row:
2
4
5
7
Matrix is:
[[2. 4.]
 [5. 7.]]
Determinant of the matrix is: -5.999999999999998


In [ ]:
def determinant_3x3(A):
    """Manual 3x3 determinant"""
    a, b, c = A[0]
    d, e, f = A[1]
    g, h, i = A[2]
    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

# Main
A = [[2, 3, 1],
     [4, 5, 6],
     [7, 8, 9]]

print("Matrix A:")
for row in A:
    print(row)

det = determinant_3x3(A)
print(f"\nDeterminant: {det}")


Matrix A:
[2, 3, 1]
[4, 5, 6]
[7, 8, 9]

Determinant: 9


In [ ]:
def determinant_3x3(A):
    a, b, c = A[0]
    d, e, f = A[1]
    g, h, i = A[2]
    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

def adjoint_3x3(A):
    adj = [[0.0]*3 for _ in range(3)]
    adj[0][0] = +(A[1][1]*A[2][2] - A[1][2]*A[2][1])
    adj[0][1] = -(A[1][0]*A[2][2] - A[1][2]*A[2][0])
    adj[0][2] = +(A[1][0]*A[2][1] - A[1][1]*A[2][0])
    adj[1][0] = -(A[0][1]*A[2][2] - A[0][2]*A[2][1])
    adj[1][1] = +(A[0][0]*A[2][2] - A[0][2]*A[2][0])
    adj[1][2] = -(A[0][0]*A[2][1] - A[0][1]*A[2][0])
    adj[2][0] = +(A[0][1]*A[1][2] - A[0][2]*A[1][1])
    adj[2][1] = -(A[0][0]*A[1][2] - A[0][2]*A[1][0])
    adj[2][2] = +(A[0][0]*A[1][1] - A[0][1]*A[1][0])
    return [[adj[j][i] for j in range(3)] for i in range(3)]

def inverse_3x3(A):
    det = determinant_3x3(A)
    if abs(det) < 1e-10:
        print("Matrix is singular!")
        return None
    adj = adjoint_3x3(A)
    return [[round(adj[i][j]/det, 4) for j in range(3)] for i in range(3)]

# Main
A = [[2, 3, 1],
     [4, 5, 6],
     [7, 8, 9]]

print("Matrix A:")
for row in A:
    print(row)

inv_A = inverse_3x3(A)
if inv_A:
    print("\nInverse:")
    for row in inv_A:
        print(row)


Matrix A:
[2, 3, 1]
[4, 5, 6]
[7, 8, 9]

Inverse:
[-0.3333, -2.1111, 1.4444]
[0.6667, 1.2222, -0.8889]
[-0.3333, 0.5556, -0.2222]


In [ ]:
def solve_gauss_jordan(A, B):
    """Manual Gauss-Jordan elimination for 2x2"""
    n = len(A)
    aug = [A[i][:] + [B[i]] for i in range(n)]

    # Forward elimination
    for i in range(n):
        if abs(aug[i][i]) < 1e-10:
            print("Singular matrix!")
            return None
        for j in range(i+1, n):
            factor = aug[j][i] / aug[i][i]
            for k in range(i, n+1):
                aug[j][k] -= factor * aug[i][k]

    # Back substitution
    x = [0.0]*n
    for i in range(n-1, -1, -1):
        x[i] = aug[i][n]
        for j in range(i+1, n):
            x[i] -= aug[i][j] * x[j]
        x[i] /= aug[i][i]
    return x

# Main: 2x + 3y = 10, 4x + 5y = 20
A = [[2, 3],
     [4, 5]]
B = [10, 20]

print("Coefficient Matrix A:")
for row in A:
    print(row)
print("Constant vector B:", B)

solution = solve_gauss_jordan(A, B)
if solution:
    print(f"Solution: x={solution[0]}, y={solution[1]}")


Coefficient Matrix A:
[2, 3]
[4, 5]
Constant vector B: [10, 20]
Solution: x=5.0, y=-0.0


In [ ]:
import numpy as np

# Take input for 3x3 matrix
print("Enter elements for 3x3 matrix:")

matrix = []

for i in range(3):
    row = []
    for j in range(3):
        num = float(input())
        row.append(num)
    matrix.append(row)

# Convert into NumPy array
matrix = np.array(matrix)

# Print matrix
print("Matrix is:")
print(matrix)

# Find inverse
inverse = np.linalg.inv(matrix)

# Print inverse
print("Inverse of matrix is:")
print(inverse)



Enter elements for 3x3 matrix:
6
7
8
4
5
3
2
1
5
Matrix is:
[[6. 7. 8.]
 [4. 5. 3.]
 [2. 1. 5.]]
Inverse of matrix is:
[[-1.57142857  1.92857143  1.35714286]
 [ 1.         -1.         -1.        ]
 [ 0.42857143 -0.57142857 -0.14285714]]


In [ ]:
import numpy as np

# Take coefficients input
print("Enter coefficients of equations:")
a1 = float(input("Enter coefficient of x in first equation: "))
b1 = float(input("Enter coefficient of y in first equation: "))
c1 = float(input("Enter constant of first equation: "))

a2 = float(input("\nEnter coefficient of x in second equation: "))
b2 = float(input("Enter coefficient of y in second equation: "))
c2 = float(input("Enter constant of second equation: "))

# Create coefficient matrix
A = np.array([
    [a1, b1],
    [a2, b2]
])

# Create constant vector
B = np.array([c1, c2])

# Solve the equations
solution = np.linalg.solve(A, B)

# Display result
print("\nSolution:")
print("x =", solution[0])
print("y =", solution[1])


Enter coefficients of equations:
Enter coefficient of x in first equation: 5
Enter coefficient of y in first equation: 6
Enter constant of first equation: 3

Enter coefficient of x in second equation: 5
Enter coefficient of y in second equation: 7
Enter constant of second equation: 8

Solution:
x = -5.4
y = 5.0


In [ ]:
import numpy as np

# Empty list for matrix
matrix = []

print("Enter elements for 3x3 matrix:")

# Input matrix elements
for i in range(3):
    row = []
    for j in range(3):
        value = float(input())
        row.append(value)
    matrix.append(row)

# Convert list to NumPy array
matrix = np.array(matrix)

# Display matrix
print("Matrix is:")
print(matrix)

# Calculate determinant
det = np.linalg.det(matrix)

# Display determinant
print("Determinant of the matrix is:", det)


Enter elements for 3x3 matrix:
7
4
5
6
9
0
1
4
5
Matrix is:
[[7. 4. 5.]
 [6. 9. 0.]
 [1. 4. 5.]]
Determinant of the matrix is: 269.99999999999983
